FileVersion = 1
Projects = {Instant = {Path = "."}, SDL2 = "*"}

[Workspace]
StartupProject = "Instant"

[Configs.Debug.wasm32]
AllocType = "CRT"
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
