FileVersion = 1
Projects = {Instant = {Path = "."}, SDL2 = "*", Examples = {Path = "Examples"}}

[Workspace]
StartupProject = "Examples"

[Configs.Debug.wasm32]
AllocType = "CRT"
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
